name: First Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build project with Maven
        run: mvn -B package --file lab1/pom.xml
      - name: Upload built artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact.jar
          path: target/lab1-1.0-SNAPSHOT.jar
